name: veezo
description: "Veezo"

version: 0.0.1+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shadcn_flutter: ^0.0.42
  flutter_hooks: ^0.21.3+1
  gpt_markdown: ^1.1.3

  flutter_dotenv: ^6.0.0
  go_router: ^16.2.1
  
  dio: ^5.9.0
  uuid: ^4.5.1
  web_socket_client: ^0.2.1
  dart_mappable: ^4.6.0
  retrofit: ^4.7.1
  injectable:
  get_it:
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  jwt_decoder: ^2.0.1
  google_sign_in: ^7.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner:
  injectable_generator:
  dart_mappable_builder: ^4.6.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.2
  swagger_parser: ^1.30.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - staging.env
    - prod.env
  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

swagger_parser:
  schema_url: http://localhost:8000/api/schema/
  output_directory: lib/generated/
  json_serializer: dart_mappable
  use_multipart_file: true